### ISSUE TITLE
About removing the reliance on the Windows app

### ISSUE THREAD

**Issue by menant** [braintapper/neewer-gl1#1]
Hi Steven,

Thank you for all your reverse-engineering work.
During your investigations, did you happen to figure out why the Windows app needs to be loaded for the light to be accepting UDP packets?

I'm interested to find a solution like your script that is decoupled from the Windows platform and the Neewer Windows app.

Thanks for your time!

**Comment by braintapper** [comment]
There's an initial handshake between Windows and the light that I can't seem to reproduce. 

If you want to do a non-Windows solution, it looks like there are some Bluetooth only options if you search Github.

**Comment by menant** [comment]
Thanks for your swift follow-up.
If I was to spend time on this and figure it out, I will let you know.

**Comment by braintapper** [comment]
Finally figured out how the handshake (and the app) works.

If you observe the traffic with Wireshark, the app sends a message 3 times to wake the light, and will then accept some commands within a small time window. This message contains the IP address of your machine.

If you don't continuously send some keep-alive heartbeat packets to the light within a short window, the light will stop listening to commands. The Neewer app does this continuously, but any script you use to control the light only needs to repeat the handshake message 3 times followed by some commands.

When I get a chance, I will update the doc and code to reflect this new knowledge.
